### ISSUE TITLE
Text domain

### ISSUE THREAD

**Issue by webmandesign** [FacetWP/use-child-theme#14]
As far as I know, there should be only 1 text domain used in a WordPress theme.

So, I suggest renaming the text domain in the script from `use-child-theme` to `parent-theme-slug` (or similar) and making a note in description that theme developer should change this text domain to match the (parent) theme (where this script is included) slug.

What do you say?

PS: I'm not really a fan of modifying scripts included in the theme, but this is the only way we can resolve this issue I think.

**Comment by mgibbs189** [comment]
See #15 - would you agree that adding a filter to control the textdomain would be the best approach?

I wasn't aware that text domains could even be dynamically generated...

**Comment by webmandesign** [comment]
I have commented on #15 

Still keeping this issue open as I really think #15 is wrong approach.

**Comment by webmandesign** [comment]
Seems like scripts included within themes have to be edited anyway. Another example is **TGM Plugin Activation** script which allows you to [configure it before you download](http://tgmpluginactivation.com/download/).

There doesn't have to be a configurator here, but we should document it.
