### ISSUE TITLE
Screencast does not show actual behavior

### ISSUE THREAD

**Issue by tnorthcutt** [FacetWP/use-child-theme#17]
_Disclaimer: super, super nitpicky detail – I understand if it's not worth bothering with_

I was initially confused because the screencast shows the notice appearing on `Appearance —> Themes`, but in reality the notice [only shows](https://github.com/FacetWP/use-child-theme/commit/2288b1a55b124b327f88dbe4f77faa1ee1c9d52c) on `Appearance —> Editor`.

**Comment by mgibbs189** [comment]
Good point @tnorthcutt, I'll get that screencast updated
