### ISSUE TITLE
Is this project dead already?

### ISSUE THREAD

**Issue by webmandesign** [FacetWP/use-child-theme#18]
Hi,

I just want to check if this project is still on. I haven't received any answer to [my previous suggestions](https://github.com/FacetWP/use-child-theme/commit/aca1103cbe1280580f3f364c69c8f0f9af5afa27#commitcomment-17235641), that's why I'm asking.

Thanks and regards,

Oliver

**Comment by mgibbs189** [comment]
Not dead, just lack of available time for it ATM. The best way to get your voice heard is through a PR :)

**Comment by webmandesign** [comment]
OK then, thanks for letting me know!
