### ISSUE TITLE
Loading files within a theme

### ISSUE THREAD

**Issue by emiluzelac** [FacetWP/use-child-theme#6]
This isn't a recommended usage:

`include( dirname( __FILE__ ) . '/use-child-theme.php' );`

Option A:
`include get_template_directory() . '/use-child-theme.php';`

Option B:
`require get_template_directory() . '/use-child-theme.php';`

**Comment by justintadlock** [comment]
I'd actually recommend the following for theme usage:

```
require_once( trailingslashit( get_template_directory() ) . 'use-child-theme.php' );
```

And, this for plugin usage:

```
require_once( trailingslashit( plugin_dir_path( __FILE__ ) ) . 'use-child-theme.php' );
```

**Comment by emiluzelac** [comment]
`trailingslashit` is a personal preference ;) But yeah, that works too!

**Comment by mgibbs189** [comment]
Thanks guys, README.md updated
