### ISSUE TITLE
Prevent XSS Vulnerability

### ISSUE THREAD

**Issue by emiluzelac** [FacetWP/use-child-theme#8]
I would recommend escaping the following in: https://github.com/FacetWP/use-child-theme/blob/master/use-child-theme.php#L52-L78

More details: 
- http://security.stackexchange.com/a/11989
- http://www.acunetix.com/websitesecurity/cross-site-scripting/
- https://vip.wordpress.com/2015/03/25/preventing-xss-in-javascript/

There's also another method as well: https://github.com/Automattic/theme-tools/blob/master/jetpack-dependency-script/plugin-enhancements.php#L234-L269

P.S. I had bit more time today :)

**Comment by mgibbs189** [comment]
@emiluzelac Thanks for submitting.

What part specifically is vulnerable to XSS? There really isn't any user inputs in the code you highlighted. `$this->theme->get( 'Name' )` is coming directly from WP...

**Comment by emiluzelac** [comment]
Sure thing @mgibbs189 it's right here: `href="javascript:;"` and it's `.on('click'` as well.

**Comment by mgibbs189** [comment]
`href="javascript:;"` just tells the browser not to do anything on click.

It's the same as `href="#"`, but doesn't scroll the page to the top.

**Comment by emiluzelac** [comment]
You did it: https://github.com/FacetWP/use-child-theme/blob/master/use-child-theme.php#L81

**Comment by emiluzelac** [comment]
Sorry for writing and deleting earlier. I see what do you mean now.
